<%info=trim(request("info"))%>
<html>
<head>
<title>出错！</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="keywords" content="同学、同学录、校友、老师、学校、班级、交流">
<STYLE type=text/css>
</STYLE>
<LINK href="scss.css" rel=stylesheet>
</head>

<body bgcolor="#FFFFFF" text="#FF0000" topmargin="5">
<div align="center">
  <center>
<table width="750" border="1" cellspacing="0" cellpadding="0" bordercolor="#003300" style="border-collapse: collapse">
  <tr> 
    <td align="center" valign="top" bgcolor="#F6F6F6"> <br>
      <br>
      <br>
      <br>
      <table width="500" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td width="80"><img src="../school_images/err.gif"></td>
          <td width="340" align="center" class="cn"><font color="#FF0000"><%=info%></font></td>
          <td width="80" align="center" class="cn">　</td>
        </tr>
      </table>
      <br>
      
      <br>
      <br>
      <table width="480" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td align="center"><font color="#000000">&lt;&lt;&lt;</font><a href="javascript:history.go(-1);"><font color="#000000">返回</font></a></td>
        </tr>
      </table>
      <br>
      <br>
      <br>
    </td>
  </tr>
</table>
  </center>
</div>
<br>
<br>
      </body>
</html>