vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|27 Jul 2003 01:37:14 -0000
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|xiaoyoulu/CLASS/class_index.asp xiaoyoulu/CLASS/ClassPhotoList.asp xiaoyoulu/CLASS/popwindow_modifyinfo.asp
vti_author:SR|AHU333-KUU8GW3K\\Administrator
vti_modifiedby:SR|AHU333-KUU8GW3K\\Administrator
vti_timecreated:TR|27 Jul 2003 01:37:14 -0000
vti_cacheddtm:TX|27 Jul 2003 01:37:14 -0000
vti_filesize:IR|22536
vti_cachedtitle:SR|Wosou校友录 
vti_cachedbodystyle:SR|<BODY bgColor=white leftMargin=0 topMargin=5 >
vti_cachedlinkinfo:VX|D|class_index.asp D|class_index.asp S|img/alumni.js Q|img/alumni.css S|img/cr_a1.gif S|img/cr_a2.gif H|javascript:login() S|img/cr_a22.gif H|javascript:login() S|img/cr_a23.gif H|../classlogout.asp S|img/cr_a22.gif H|../classlogout.asp S|img/c.gif S|img/c.gif S|img/c.gif Q|img/photo.css S|img/cla_bg3.gif H|popwindow_modifyinfo.asp H|ClassBBSList.asp H|class_phonebook.asp H|PopWindowEmailList.asp H|ClassPhotoList.asp H|javascript:PopWindowUpload(); H|tj.asp H|javascript:manage(); H|../register.htm H|../schoollist.asp H|../find_class1.asp H|../classlist.asp S|img/cla_a1.gif H|ClassBBSList.asp S|img/cla_a40.gif H|ClassBBSList.asp S|img/cla_a33.gif H|class_phonebook.asp S|img/cla_a41.gif H|class_phonebook.asp S|img/cla_a33.gif H|popwindow_search.html S|img/cla_a42.gif H|popwindow_search.html S|img/cla_a33.gif H|PopWindowEmailList.asp S|img/cla_a43.gif H|PopWindowEmailList.asp S|img/cla_a33.gif H|javascript:manage(); S|img/cla_a44.gif H|javascript:manage(); S|img/cla_a33.gif H|ClassPhotoList.asp S|img/cla_a46.gif H|ClassPhotoList.asp S|img/cla_a33.gif H|javascript:PopWindowUpload(); S|img/cla_a45.gif H|javascript:PopWindowUpload(); S|img/cla_a33.gif H|popwindow_modifyinfo.asp S|img/cla_a47.gif H|popwindow_modifyinfo.asp S|img/cla_a33.gif H|popwindow_modifyinfo.asp S|img/cla_a48.gif H|popwindow_modifyinfo.asp S|img/cla_a33.gif H|../find_class1.asp S|img/cla_a49.gif H|../find_class1.asp H|ClassPhotoView.asp H|javascript:personalinfo('<%=rs("UserID")%>'); H|del.asp H|ClassPhotoList.asp H|ClassPhotoList.asp H|ClassPhotoList.asp H|ClassPhotoList.asp S|img/c.gif
vti_cachedsvcrellinks:VX|FDUS|xiaoyoulu/CLASS/class_index.asp FDUS|xiaoyoulu/CLASS/class_index.asp NSUS|xiaoyoulu/CLASS/img/alumni.js FQUS|xiaoyoulu/CLASS/img/alumni.css FSUS|xiaoyoulu/CLASS/img/cr_a1.gif FSUS|xiaoyoulu/CLASS/img/cr_a2.gif SHUS|javascript:login() FSUS|xiaoyoulu/CLASS/img/cr_a22.gif SHUS|javascript:login() NSUS|xiaoyoulu/CLASS/img/cr_a23.gif FHUS|xiaoyoulu/classlogout.asp FSUS|xiaoyoulu/CLASS/img/cr_a22.gif FHUS|xiaoyoulu/classlogout.asp FSUS|xiaoyoulu/CLASS/img/c.gif FSUS|xiaoyoulu/CLASS/img/c.gif FSUS|xiaoyoulu/CLASS/img/c.gif FQUS|xiaoyoulu/CLASS/img/photo.css FSUS|xiaoyoulu/CLASS/img/cla_bg3.gif FHUS|xiaoyoulu/CLASS/popwindow_modifyinfo.asp FHUS|xiaoyoulu/CLASS/ClassBBSList.asp FHUS|xiaoyoulu/CLASS/class_phonebook.asp FHUS|xiaoyoulu/CLASS/PopWindowEmailList.asp FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp SHUS|javascript:PopWindowUpload(); FHUS|xiaoyoulu/CLASS/tj.asp SHUS|javascript:manage(); FHUS|xiaoyoulu/register.htm FHUS|xiaoyoulu/schoollist.asp FHUS|xiaoyoulu/find_class1.asp FHUS|xiaoyoulu/classlist.asp FSUS|xiaoyoulu/CLASS/img/cla_a1.gif FHUS|xiaoyoulu/CLASS/ClassBBSList.asp FSUS|xiaoyoulu/CLASS/img/cla_a40.gif FHUS|xiaoyoulu/CLASS/ClassBBSList.asp FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/CLASS/class_phonebook.asp FSUS|xiaoyoulu/CLASS/img/cla_a41.gif FHUS|xiaoyoulu/CLASS/class_phonebook.asp FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/CLASS/popwindow_search.html FSUS|xiaoyoulu/CLASS/img/cla_a42.gif FHUS|xiaoyoulu/CLASS/popwindow_search.html FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/CLASS/PopWindowEmailList.asp FSUS|xiaoyoulu/CLASS/img/cla_a43.gif FHUS|xiaoyoulu/CLASS/PopWindowEmailList.asp FSUS|xiaoyoulu/CLASS/img/cla_a33.gif SHUS|javascript:manage(); FSUS|xiaoyoulu/CLASS/img/cla_a44.gif SHUS|javascript:manage(); FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp FSUS|xiaoyoulu/CLASS/img/cla_a46.gif FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp FSUS|xiaoyoulu/CLASS/img/cla_a33.gif SHUS|javascript:PopWindowUpload(); FSUS|xiaoyoulu/CLASS/img/cla_a45.gif SHUS|javascript:PopWindowUpload(); FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/CLASS/popwindow_modifyinfo.asp FSUS|xiaoyoulu/CLASS/img/cla_a47.gif FHUS|xiaoyoulu/CLASS/popwindow_modifyinfo.asp FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/CLASS/popwindow_modifyinfo.asp FSUS|xiaoyoulu/CLASS/img/cla_a48.gif FHUS|xiaoyoulu/CLASS/popwindow_modifyinfo.asp FSUS|xiaoyoulu/CLASS/img/cla_a33.gif FHUS|xiaoyoulu/find_class1.asp FSUS|xiaoyoulu/CLASS/img/cla_a49.gif FHUS|xiaoyoulu/find_class1.asp FHUS|xiaoyoulu/CLASS/ClassPhotoView.asp SHUS|javascript:personalinfo('<%=rs("UserID")%>'); FHUS|xiaoyoulu/CLASS/del.asp FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp FHUS|xiaoyoulu/CLASS/ClassPhotoList.asp FSUS|xiaoyoulu/CLASS/img/c.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Language zh-cn HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312 GENERATOR Microsoft\\ FrontPage\\ 5.0
vti_charset:SR|gb2312
vti_language:SR|zh-cn
vti_generator:SR|Microsoft FrontPage 5.0
vti_title:SR|Wosou校友录 
vti_lineageid:SR|{B279A31E-F909-4422-9845-715A9F5761E9}
