vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Jul 2003 15:42:38 -0000
vti_extenderversion:SR|5.0.2.2623
vti_author:SR|AHU333-KUU8GW3K\\Administrator
vti_modifiedby:SR|AHU333-KUU8GW3K\\Administrator
vti_timecreated:TR|22 Jul 2003 15:42:38 -0000
vti_cacheddtm:TX|22 Jul 2003 15:42:38 -0000
vti_filesize:IR|3356
vti_cachedtitle:SR|Wosou校友录
vti_cachedbodystyle:SR|<BODY BGCOLOR=#FFFFFF leftmargin="0" topmargin="0">
vti_cachedlinkinfo:VX|Q|../scss.css H|javascript:history.go(-1) H|javascript:window.close()
vti_cachedsvcrellinks:VX|NQUS|scss.css SHUS|javascript:history.go(-1) SHUS|javascript:window.close()
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312 keywords 同学、同学录、校友、老师、学校、班级、交流
vti_charset:SR|gb2312
vti_title:SR|Wosou校友录
vti_lineageid:SR|{04FE1A4B-6777-4302-9D43-A99150BEECE4}
vti_backlinkinfo:VX|
